spring:
  application:
    name: AnyDay Database Service

  datasource:
    url: jdbc:mysql://localhost:3307/AnyDay
    driver-class-name: com.mysql.cj.jdbc.Driver

    # TODO: Use username/password from environment variables
    username: root 
    password: password 

  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    show-sql: true

